### ISSUE TITLE
How can I solve following font?

### ISSUE THREAD

**Issue by xsisec** [janjoswig/Ducula#2]
![2020-03-1403⁄14⁄2016-50-18](https://user-images.githubusercontent.com/17006430/76685442-eaec7c00-6613-11ea-8b35-f27beeeff57c.png)

**Comment by xsisec** [comment]
the theme doesnt diplay the icons :(

**Comment by janjoswig** [comment]
You probably just need to install a font that can display the missing symbols, for example [Noto Color Emoji](https://www.google.com/get/noto/#emoji-zsye-color). Maybe you also need to make adjustments to your [fontconfig](https://askubuntu.com/questions/963840/how-do-i-configure-the-default-emoji-font-to-be-used-in-os-browser-its-curren).
